---
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Breaking Changes'
    labels:
      - 'major'
  - title: 'Features'
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'documentation'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'chore'
      - 'dependencies'
      - 'documentation'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
